#! /bin/sh

rofi_cmd() {
	rofi -dmenu \
		-theme ~/.config/rofi/configs/power.rasi
}

chosen=$(printf "\n\n" | rofi_cmd)

case "$chosen" in
	"") loginctl poweroff ;;
	"") loginctl reboot ;;
	"") betterlockscreen -l dim ;;
	*) exit 1 ;;
esac
